# Generated by Django 3.1.7 on 2021-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
