# Generated by Django 3.1.7 on 2021-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210323_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
