version: "3.9"

services:
  src:
    restart: always
    container_name: src
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socialnetwork

volumes:
  postgres_data:
